version: '3.8'

services:
  jobmanager:
    image: flink:2.0.0-scala_2.12-java21 # image version
    hostname: jobmanager
    container_name: flink-jobmanager
    command: jobmanager
    ports:
      - "8081:8081"
      - "6123:6123"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.bind-port: 8081
        rest.address: 0.0.0.0
    volumes:
      - ./target:/opt/flink/usrlib
    networks:
      - flink-network

  taskmanager:
    image: flink:2.0.0-scala_2.12-java21 # image version
    hostname: taskmanager
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 1
    volumes:
      - ./target:/opt/flink/usrlib
    networks:
      - flink-network

networks:
  flink-network:
    driver: bridge